# A portable environment file for the ZHAW-DSF Summer School project.
# This version is simplified to work on any operating system (like the Linux used by MyBinder).
name: ZHAW-DSF-Summer-School

channels:
  # It's good practice to prioritize conda-forge.
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # === Core Setup ===
  - python=3.12
  - ipykernel # Essential for running Jupyter notebooks

  # === Common Data Science Libraries ===
  # Add or remove packages based on your actual needs.
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - plotly

  # === PyTorch for Deep Learning ===
  # These are best installed from the pytorch conda channel.
  - pytorch
  - torchvision
  - pytorch-cuda=12.1 # Specify CUDA version for GPU support if needed

  # === For adding packages from PyPI ===
  - pip
  - pip:
    - beautifulsoup4
    - bertopic
    - curl-cffi
    - hdbscan
    - huggingface-hub
    - nltk
    - sentence-transformers
    - transformers
    - umap-learn
    - wordcloud
    - yfinance
